# Name for your workflow
name: My First GitHub Action

# Controls when the action will run
on:
  # Triggers the workflow on push events for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" job
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # This is the custom step with your email as the name
      - name: 21f1005212@ds.study.iitm.ac.in
        run: echo "This step is named with my email address!"

      - name: A final step
        run: echo "Action completed successfully."
